config/routes.rb
Rails.application.routes.draw do
  	
  

  get 'payment_select/select_plan'

  get 'payment_select/select_monthly_subscription'

  get 'select_movies/index'

  devise_for :users

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  get '/select_plan' => 'payment_select#select_plan', as: :select_plan



  get '/about' => 'statics#about', :as => :about

  get 'statics/index'

  # get 'statics/about'

  get 'peliculas/index'

  get 'settings/index'

  resources :charges
    resources :select_movies, only: :index

  resources :peliculas do 
    resources :comentarios
  end
  resources :settings

  resources :statics

  

  root :to => "peliculas#index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flash_messages.html.erb
<div class="row">
  <div class="col-sm-12">
    <% flash.each do |type, message| %>
      <% unless message.blank? %>
      <div id="flashmensaje" class="alert <%= bootstrap_class_for(type) %> fade in">
        <button class="close" data-dismiss="alert">×</button>
        <%= message.html_safe %>
      </div>
      <% end %>
    <% end %>
  </div>
</div>
 
<script type="text/javascript">
  $(document).ready(function(){
    setTimeout(function(){
      $('#flashmensaje').remove();
    }, 5000);
  })
</script>

app/views/shared/_footer.html.erb
<div class="footer">
	<footer>Created and designed by Stefano Cattoni with a lot of help.<br> Copyright sforstefano 2017<br/><br/></footer>
	<a href="https://twitter.com/sforstefano/"><p class="tw">Twitter<p></a><a href="https://www.instagram.com/sforstefano/"><p class="ig">Instagram</p></a>
</div>

app/views/shared/_header.html.erb
<div class="header">
	<div class="hidden-xs">
		<% if user_signed_in? %>
			<nav class="navbar navbar-default">
				<ul class="nav navbar-nav">
					<li><%=link_to "Inicio", root_path %></li>
					<li><%= link_to "Añadir pelicula", new_pelicula_path %></li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li><%= link_to "Comprar", select_movies_path %></li>
					<li> <%=link_to "Editar usuario",  settings_path %></li>
					<li> <%= link_to image_tag("http://res.cloudinary.com/se-or/image/upload/v1498647679/1498665515_basics-17_wsvhgx.png"), destroy_user_session_path, method: :delete %> </li>
				</ul>
			</nav>
<div class="container" align="center">
	<img align="middle" src="http://res.cloudinary.com/se-or/image/upload/v1496246942/fondo_ua1eam.jpg">
</div>
	</div>
		<div class="visible-xs">
			<nav class="navbar navbar-default">
				<ul class="nav navbar-nav">
					<button class="hd-xs"><%= link_to "Pelicula", new_pelicula_path %></button>>
					<button class="hd-xs"> <%=link_to "Editar",  edit_user_registration_path %></button>>

					<button class="hd-xs"> <%= link_to image_tag("http://res.cloudinary.com/se-or/image/upload/v1498647679/1498665515_basics-17_wsvhgx.png"), destroy_user_session_path, method: :delete %></button>
				</ul>
			</nav>
		</div>
		<% else %>
			<div class="hidden-xs">
				<nav class="navbar navbar-default">
					<ul class="nav navbar-nav">
						<li><%=link_to "Entrar", new_user_session_path %></li>
						<li> <%=link_to "Registrate", new_user_registration_path %></li>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						<li><%= link_to "Nosotros", about_path %></li>
					</ul>
				</nav>
<div class="container" align="center">
	<img align="middle" src="http://res.cloudinary.com/se-or/image/upload/v1496246942/fondo_ua1eam.jpg">
</div>
			</div>
			<div class="visible-xs">
				<nav class="navbar navbar-default">
					<ul class="nav navbar-nav">
						<li class="hd-xs"><%=link_to "Entrar", new_user_session_path %></li>
						<li class="hd-xs"> <%=link_to "Registrate", new_user_registration_path %></li>
					</ul>
					<ul class="nav navbar-nav navbar-right">
						<li class="hd-xs"><%= link_to "Nosotros", about_path %></li>
					</ul>
				</nav>
			</div>
		<% end %>
</div>