config/routes.rb
Rails.application.routes.draw do
  	
  

  get 'payment_select/select_plan'

  get 'payment_select/select_monthly_subscription'

  get 'select_movies/index'

  devise_for :users

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  get '/select_plan' => 'payment_select#select_plan', as: :select_plan



  get '/about' => 'statics#about', :as => :about

  get 'statics/index'

  # get 'statics/about'

  get 'peliculas/index'

  get 'settings/index'

  resources :charges
    resources :select_movies, only: :index

  resources :peliculas do 
    resources :comentarios
  end
  resources :settings

  resources :statics

  

  root :to => "peliculas#index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/setting.rb
class Setting < ApplicationRecord
  belongs_to :user
  validates :country, presence: { message: :no_country}
  validates :language, presence: { message: :no_language}
  validates :country, length: { minimum: 2, message: :too_short }
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
	layout 'admin'
	 
	def index

		@setting = current_user.setting
		@payment =  current_user.payments

		
		#Mostar on tneim els erors puts "=" * 500
		
		

		## Mostrar errors
		# puts "=" * 100
		# 	if @setting.country == "España"
		# 		puts "si"
		# 	else
		# 		puts "No"
		# 		puts @setting.country
		# 	end
		# puts "=" * 100

	end

	def show
		@setting = Setting.find(params[:id])
	end

	def new
		@setting = current_user.build_setting
		
	end

	def create
		@setting = current_user.build_setting(setting_params)
		if @setting.save
			redirect_to settings_path
		else
			flash[:error] = t('mal')
			render :new
		end
	end

	def edit
		@setting = Setting.find(params[:id])
	end

	def update
		@setting = Setting.find(params[:id])

		if @setting.update_attributes(setting_params)
			redirect_to settings_path
		else
			render :index
		end
	end


	private
	def setting_params
		params.require(:setting).permit(:country, :language)
	end  

end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/views/settings/edit.html.erb
<style type="text/css">
	input[type=text], select {
    width: 40%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 5px;
    box-sizing: border-box;
    margin: 0 auto;
    }

    input[type=submit] {
    width: 15%;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    }
</style>

    <% if flash.present? %>
        <div class="row">
            <div class="col-sm-12 col-md-6 colmd-offset-3" style="padding:25px 0">
            <%= render partial: "shared/flash_messages", flash: flash %>
        </div>
    <% end %> 

<div class="container">
	<div class="col-lg-12 col-xs-12">
		<div class="editar"> 		
			<br/>
			<br/>
			<%= form_for @setting do |x|%>
				<h3>País:</h3>
				<div class="field">         	 
				    <%= x.select :country, options_for_country, :prompt => 'Escoje país', class:'form-control' %>
				</div> 
				<br/>
				<br/>
				<h3>Idioma:</h3>
				<p><%= x.text_field :language %></p>
				<br/>
				<div align="center">	
				<p><%= x.submit "Guardar" %></p>
				</div>	 
			<%end%>
		</div>
	</div>
</div>

app/views/settings/index.html.erb
 <div class="container">
 	<% if flash.present? %>
	<div class="row">
		<div class="col-sm-12 col-md-6 colmd-offset-3" style="padding:25px">
		<%= render partial: "shared/flash_messages", flash: flash %>
	</div>
	<% end %>	
	 <div class="show"> 
		 <div class="col-lg-6">
			 <div class="showPeli">
				 <%if !@setting.nil?%>
				 
				   	 <p>País: <%= @setting.country %></p>
				   	 <br/>
				   	 <p>Idioma: <%= @setting.language %></p>
				   	 <br/>
				 
				     <p><%= link_to ' Editar', edit_setting_path(@setting.id) %></p>
				    
				 <%else%>
				 
				   	<%= link_to 'Añadir', new_setting_path %>
				 <%end%>
			 </div>
		 </div>
	 </div>
	 	<% if !@payment.nil? %>
			<h2>Payments</h2>
				<%@payment.each do |payment|%>
					<p><b>Subscription active:</b></p>
					<p><%= payment.subscription %></p>
					<p><b>Payment Channel:</b></p>
					<p><%= payment.channel %></p>
					<p><b>Payment active:</b></p>
					<p><%= payment.active %></p>
					<p><b>Plan:</b></p>
					<p><%= payment.plan %></p> 
					<p><b>Amount payed:</b></p>
					<p><%= payment.amount %></p>
					<hr>				
				<%end%>
		<%end%>

 </div>

app/views/settings/new.html.erb
<style type="text/css">
    input[type=text], select {
    width: 40%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 5px;
    box-sizing: border-box;
    margin: 0 auto;
    }
    input[type=submit] {
    width: 15%;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    }
</style>

<div class="container"> 

    <% if flash.present? %>
        <div class="row">
            <div class="col-sm-12 col-md-6 colmd-offset-3" style="padding:25px 0">
            <%= render partial: "shared/flash_messages", flash: flash %>
        </div>
    <% end %> 


</div>        

<div class="container">
    <div class="col-lg-12 col-xs-12">
        <div class="editar">        
            <br/>
            <br/>
            <%= form_for @setting do |x|%>
                <h3>País:</h3>
                <div class="field">              
                    <%= x.select :country, options_for_country, :prompt => 'Escoje país', class:'form-control' %>
                </div> 
                <br/>
                <br/>
                <h3>Idioma:</h3>
                <p><%= x.text_field :language %></p>
                <br/>   
                <div align="center">
                <p><%= x.submit "Guardar" %></p>  
                </div> 
                <br/>
                <br/>  
            <%end%>
        </div>
    </div>
</div>