config/routes.rb
Rails.application.routes.draw do
  	
  

  get 'payment_select/select_plan'

  get 'payment_select/select_monthly_subscription'

  get 'select_movies/index'

  devise_for :users

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  get '/select_plan' => 'payment_select#select_plan', as: :select_plan



  get '/about' => 'statics#about', :as => :about

  get 'statics/index'

  # get 'statics/about'

  get 'peliculas/index'

  get 'settings/index'

  resources :charges
    resources :select_movies, only: :index

  resources :peliculas do 
    resources :comentarios
  end
  resources :settings

  resources :statics

  

  root :to => "peliculas#index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/select_movies_controller.rb
class SelectMoviesController < ApplicationController
	before_action :authenticate_user!
  def index
  	  if params[:search]
         @peliculas = Pelicula.search(params[:search])
      elsif params[:search_year]
      	 @peliculas = Pelicula.search_year(params[:search_year])
      elsif params[:search_genre]
      	 @peliculas = Pelicula.search_genre(params[:search_genre]).order("created_at DESC")
      else
      	 @peliculas = Pelicula.all
      end
  end
end

app/helpers/select_movies_helper.rb
module SelectMoviesHelper
end

app/views/select_movies/index.html.erb
<div class="container">
	<div class="row">
	  <div class="col-lg-4 col-sm-12">
	    <%= form_tag(select_movies_path, :method => "get", id: "search-form") do %>
	        <%= text_field_tag :search, params[:search], placeholder: "Buscar por actor" %>
	        	<%= submit_tag "Buscar" %>
	    <% end %>
	  </div>
	  <div class="col-lg-4 col-sm-12">

	    <%= form_tag(select_movies_path, :method => "get", id: "search-year-form") do %>
    		<%= text_field_tag :search_year, params[:search_year], placeholder: "Buscar por año"  %>
    			<%= submit_tag "Buscar" %>
	    <% end %>
	   </div>

	    <div class="col-lg-4 col-xs-12">
		<%= form_tag(select_movies_path, :method => "get", id: "search-genre-form") do %>
			<%= select_tag :search_genre, ("<option>Selecciona por género</option><br><option>Drama</option><option>Fantasia</option><option>Comedia</option><option>Animación</option><option>Romántico</option><option>Acción</option><option>Terror</option><option>Musical</option><option>Aventura</option><option>Ciencia ficción</option><option>Suspense</option><option>Bélico</option><option>Western</option>").html_safe, class: 'btn btn-default', :onchange => "this.form.submit()"%>
			<% end %>

		</div>

	    <br/>
	  </div>
</div>
<br/>
<br>

	<div class="container">
		<div class="row">
			<div align="center">
			    <% @peliculas.each do |peli| %>
				    <% if peli.precio != 0 %>
					    <div class="col-sm-12 col-md-4 col-lg-4">
					        <div class="select-movie">
					            <a href="<%= pelicula_path(peli) %>"><img src="<%=peli.url%>"></a>
								<p><b><%= link_to peli.name, peli %></b></p>
		 						<%= link_to select_plan_path(movie: peli.id, user: current_user), class: "btn btn-default btn-md" do %>
		  						<i class="fa fa-film"></i> 
			  						<% if peli.precio != nil %>
			  						 <%= peli.precio/100.0 %> €
			  						<% end %>
		  						<% end %>
					        </div>
					        <br/>
					        <br/>
					        <br/>
					    </div>
					<% end %>
			    <% end %>
			</div>
		</div>
	</div>