config/routes.rb
Rails.application.routes.draw do
  	
  

  get 'payment_select/select_plan'

  get 'payment_select/select_monthly_subscription'

  get 'select_movies/index'

  devise_for :users

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  get '/select_plan' => 'payment_select#select_plan', as: :select_plan



  get '/about' => 'statics#about', :as => :about

  get 'statics/index'

  # get 'statics/about'

  get 'peliculas/index'

  get 'settings/index'

  resources :charges
    resources :select_movies, only: :index

  resources :peliculas do 
    resources :comentarios
  end
  resources :settings

  resources :statics

  

  root :to => "peliculas#index"
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pelicula.rb
class Pelicula < ApplicationRecord
	has_many :comentarios

	def self.search(search)
     	where("main_actor like ?", "%" + "%#{search}%" + "%")
   	end

  def self.search_year(search_year)
   where(year: search_year)
  end

  def self.search_genre(search_genre)
    where("genre like ?", "%" + "%#{search_genre}%" + "%")
  end

  validates :name, :stars, :main_actor, :year, :url, :genre, :director, :precio, :original, presence: {mesage: "No puedes dejar bacío"}
  validates :stars, :year, :precio, numericality: { only_integer: true }
  validates :stars, numericality: { less_than_or_equal_to: 5, message:"No puede ser mayor a 5" }
  validates :year, numericality: { greater_than: 1899, less_than_or_equal_to: 2030 }
  validates :name, :main_actor, :original, length: { maximum: 50 }
end

app/controllers/peliculas_controller.rb
class PeliculasController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]
   def index
      @peliculas = Pelicula.all
      #muestra las peliculas que hay en la base de datos
   end


   
   def show
      @pelicula = Pelicula.find(params[:id])
      #muestra una pelicula
   end
   
   def new
      @pelicula = Pelicula.new
      #crea una pelicula
   end
   
   def create
      @pelicula = Pelicula.new(pelicula_params)
      #no tiene vista, procesa la pelicula
      if @pelicula.save
         redirect_to root_path, :notice => "Se ha guardado la peli"
      else
         render "new"
      end
   end
   
   def edit
      @pelicula = Pelicula.find(params[:id])
      #actualiza la peli
   end
   
 
   def update
      @pelicula = Pelicula.find(params[:id])
    
      if @pelicula.update_attributes(pelicula_params)
         redirect_to root_path, :notice => "éxito!"
      else
       render "edit"
      end
   end

   
   def destroy
      @pelicula = Pelicula.find(params[:id])
      @pelicula.destroy
      redirect_to root_path, :notice => "Eliminado"

      #render "index"
   end

   private

      def pelicula_params
            params.require(:pelicula).permit(:name, :main_actor, :stars, :year, :url, :director, :sinopsis, :original, :genre, :precio )
      end

end

app/helpers/peliculas_helper.rb
module PeliculasHelper
	
end

app/views/peliculas/edit.html.erb
<div class="container">
		<div class="col-lg-6 col-md-6 col-xs-12">
			<div class="editar"> 
				
				<br/>
				<br/>
				<%= form_for @pelicula do |pelic| %>
					<p>Titulo</p>
					<p><%= pelic.text_field :name, placeholder:"Título"  %></p>
					<br/>
					<p><%= pelic.text_field :original, placeholder:"Titulo original" %></p>
					<br/>
					<p>Genero</p>
					<p><%= pelic.select :genre, options_for_genre, :prompt => 'Género', class:'form-control' %></p>
					<br/>
					<p>Director</p>
					<p><%= pelic.text_field :director, placeholder:"Director" %></p>
					<br/>
					<p>Puntuación</p>
					<p><%= pelic.select :stars, options_for_score, :prompt => 'Puntuación', class:'form-control' %></p>
					<br/>
					<p>Proagonista</p>
					<p><%= pelic.text_field :main_actor, placeholder: "Actor principal" %></p>
					<br/>
					<p>Sinopsis</p>
					<p><%= pelic.text_area :sinopsis,  placeholder: "Sinopsis", size: '60x4' %></p>
					<br/>
					<p>Año</p>
					<p><%= pelic.text_field :year, placeholder: "Año" %></p>
					<br/>	
					<p>Poster</p>
					<p><%= pelic.text_field :url, placeholder: "URL" %></p>	
					<br/>
					<p>Precio</p>
					<p><%= pelic.text_field :precio, placeholder: "Precio" %></p>
					<br/>
				<%= pelic.submit "Guardar pelicula" %>
				<%end%>
			</div>
		</div>
		<div class="hidden-xs">
			<div class="col-lg-6 col-md-6">
				<h3>Actual</h3>
				<br/>
					<div class="col-lg-6 col-md-6">
						<div class="currentPeli">
							<p><%= @pelicula.name %></p>
							<br/>
							<p><%= @pelicula.original %></p>
							<br/>
							<p><%= @pelicula.genre %></p>
							<br/>
							<p><%= @pelicula.director %></p>
							<br/>
							<p>Estrellas: <%= @pelicula.stars %></p>
							<br/>
							<p>Protagonizada por <%= @pelicula.main_actor %></p>
							<br/>
							<p><%= @pelicula.sinopsis %></p>
							<br/>
							<p><%= @pelicula.year %></p>
							<br/>
						</div>
					</div>
					<div class="col-lg-6 col-md-6">
						<%= image_tag @pelicula.url %>
					</div>
					<div class="col-lg-6 col-md-6">
					</div>
					<br/>
			</div>
		</div>
</div>
</div>
<br/>

app/views/peliculas/index.html.erb
<br/>
<br/>
<br/>
<div class="container">
	<div class="row">
			<div class="col-lg-12 col-xs-12">
				<div class="lista">
					<h3 class="todo"><%= link_to "Nuestras peliculas", statics_path %></h3>
					<br/>
					<% @peliculas.limit(10).each do |pelis| %>
						<div class="peliculas">
							<h5 class="titulo"><%= link_to pelis.name, pelis %></h5>
						</div>
					<% end %>
				</div>
			</div>
	</div>
	<br/>
	<br/>
	<div class="row">
		<div class="col-lg-4 col-md-4 col-xs-12">
				<div class="year">
					<h4 class="number">Lo mejor de 2017</h4>
					<% @peliculas.each do |peli| %>
						<% if peli.year === 2017 && peli.stars === 5 %>
							<div class="peliculas">
								<h5 class="titulo"><%= link_to peli.name, peli %></h5>
							</div>
						<% end %>
					<% end %>
				</div>
		</div>

		<div class="col-lg-6 col-md-6 col-xs-12">
				<div class="top-time">
					<h4 class="top-time-title">Top Movies of All Times</h4>
					<% @peliculas.each do |peli2| %>
						<% if peli2.stars === 5 %>
					<div class="peliculas">
						<h5 class="titulo"><%= link_to peli2.name, peli2 %></h5>
					</div>
					<% end %>
					<% end %>
				</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-4 col-md-4 col-xs-12">
			<div class="year">
				<h4 class="number">Lo mejor de 2016</h4>
					<% @peliculas.each do |peli3| %>
						<% if peli3.year === 2016 && peli3.stars === 5 %>
							<div class="peliculas">
								<h5 class="titulo"><%= link_to peli3.name, peli3 %></h5>
							</div>
						<% end %>
					<% end %>
				</h4>
			</div>
		</div>
	</div>
</div>

app/views/peliculas/new.html.erb
<div class="container">
	<div class="hidden-xs">
		<div class="crear">
			<%= form_for @pelicula do |futbol| %>
						<p>Titulo</p>
							<p><%= futbol.text_field :name  %></p>
						<br/>
						<p>Titulo original</p>
							<p><%= futbol.text_field :original %></p>
						<br/>
						<p>Genero</p>             
                   			<p><%= futbol.select :genre, options_for_genre, :prompt => 'Género', class:'form-control' %></p>
                   		<br/>
						<p>Director</p>
							<p><%= futbol.text_field :director %></p>
						<br/>
						<p>Puntuación</p>
							<p><%= futbol.select :stars, options_for_score, :prompt => 'Puntuación', class:'form-control' %></p>
						<br/>
						<p>Protagonista</p>
							<p><%= futbol.text_field :main_actor %></p>
						<br/>
						<p>Siopsis</p>
							<p><%= futbol.text_area :sinopsis, size: "60x4" %></p>
						<br/>
						<p>Año</p>
							<p><%= futbol.text_field :year %></p>
						<br/>
						<p>Poster</p>
							<p><%= futbol.text_field :url %></p>
						<p>Precio</p>
							<p><%= futbol.text_field :precio %></p>	
			<%= futbol.submit "Guardar" %>
			<% end %>
			<br/><br/><br/><br/>
		</div>
	</div>
</div>
<div class="col-xs-12 visible-xs">
<p class="xsAviso">No disponible en versión mobil.</p>
<br/>
</div>

app/views/peliculas/show.html.erb
<div class="container">
	<div class="peliShow">
		<div class="title">
			<h1><%= @pelicula.name %></h1>
			<h4><%= @pelicula.original %></h4>
				<% if @pelicula.stars == 5 %>
					<img src="http://res.cloudinary.com/se-or/image/upload/c_scale,w_30/v1498470700/Stars_pnb0hq.png"><img src="http://res.cloudinary.com/se-or/image/upload/c_scale,w_30/v1498470700/Stars_pnb0hq.png"><img src="http://res.cloudinary.com/se-or/image/upload/c_scale,w_30/v1498470700/Stars_pnb0hq.png"><img src="http://res.cloudinary.com/se-or/image/upload/c_scale,w_30/v1498470700/Stars_pnb0hq.png">
					<img src="http://res.cloudinary.com/se-or/image/upload/c_scale,w_30/v1498470700/Stars_pnb0hq.png">
				<% elsif @pelicula.stars == 4 %>
					<img src="http://res.cloudinary.com/se-or/image/upload/c_scale,w_30/v1498470700/Stars_pnb0hq.png"><img src="http://res.cloudinary.com/se-or/image/upload/c_scale,w_30/v1498470700/Stars_pnb0hq.png"><img src="http://res.cloudinary.com/se-or/image/upload/c_scale,w_30/v1498470700/Stars_pnb0hq.png"><img src="http://res.cloudinary.com/se-or/image/upload/c_scale,w_30/v1498470700/Stars_pnb0hq.png">
				<% elsif  @pelicula.stars == 3 %>
					<img src="http://res.cloudinary.com/se-or/image/upload/c_scale,w_30/v1498470700/Stars_pnb0hq.png"><img src="http://res.cloudinary.com/se-or/image/upload/c_scale,w_30/v1498470700/Stars_pnb0hq.png"><img src="http://res.cloudinary.com/se-or/image/upload/c_scale,w_30/v1498470700/Stars_pnb0hq.png">
				<% elsif @pelicula.stars == 2 %>
					<img src="http://res.cloudinary.com/se-or/image/upload/c_scale,w_30/v1498470700/Stars_pnb0hq.png"><img src="http://res.cloudinary.com/se-or/image/upload/c_scale,w_30/v1498470700/Stars_pnb0hq.png">
				<% elsif @pelicula.stars == 1 %>
					<img src="http://res.cloudinary.com/se-or/image/upload/c_scale,w_30/v1498470700/Stars_pnb0hq.png">
				<% else %>
				 	Sin puntiación
				<% end %>
		</div>
		
			<div class="show">
				<div class="col-lg-4">
					<div class="poster">
						<p><%= image_tag @pelicula.url %></p>
					</div>
				</div>
				<div class="col-lg-8">
					<div class="showPeli">
						<p>Director <%= @pelicula.director %></p>
						<br/>
						<p>Protagonizada por <%= @pelicula.main_actor %></p>
						<br/>
						<p><%= @pelicula.year %></p>
						<br/>
						<p><%= @pelicula.genre %></p>
						<br/>
						<p><%= @pelicula.sinopsis %></p>
						<br/>


					</div>
				</div>
				<div class="col-lg-4 visible-lg">
					<% if user_signed_in? %>
						<button><%= link_to "Editar Pelicula", edit_pelicula_path %></button>
						<button><%= link_to 'Borrar pelicula', pelicula_path(@pelicula), :method => :delete %></button>
					<% end %>
				</div>
			</div>
	</div>

</div>
	<br/>
	<br/>
	<br/>

	<%= render @pelicula.comentarios %>



<!-- AÑADIR COMENTARIOS -->
<%= render "comentarios/form" %>